### ISSUE TITLE
EPaxos Performance Measurement

### ISSUE THREAD

**Issue by Stuart0l** [xlab-uiuc/slooo#1]
I re-ran some of the measurements in the [EPaxos Revisited](https://www.usenix.org/system/files/nsdi21-tollman.pdf) paper. The main difference from the original EPaxos paper is that they are run in a WAN environment.

## Settings
All experiments are run on 5 server machines and 5 client machines, located at 5 datacenters in the world (WA, CA, VA, UK, JP), with 1 server and 1 client in each datacenter. Each client only sends requests to the server in its own datacenter. All servers are of the `Standard D4s v3` type, with 4 vCPUs and 16G RAM each. In each experiment, I captured metrics for 60 seconds at steady-state (run for 120s and drop the first and last 30s).

I ran two sets of experiments. One is running different workloads with the same number of clients. Four workloads are tested.

1. Zipfian: 0.9 skew, 1 million unique keys in Zipfian distribution, 50% write operations
2. 0% conflict keys: 50% write operations
3. 2% conflict keys: 50% write operations
4. 100% conflict keys: 50% write operations

There are 10 clients at each client machine. Every client only issues operations to the server machine in the same data center.

Another is running the same workload with a different number of clients. I tested the Zipfian workload with 0.9 and 0.6 skew, 1m unique keys, and 50% and 10% operations, using up to 900 clients.

### Experiment 1
The following shows the throughput and 99% execution latency of in each datacenter:
![image](https://user-images.githubusercontent.com/30303108/119016732-dc92b080-b9cc-11eb-94f3-1a36e5bcefe4.png)
The following is taken from Fig. 6 in EPaxos Revisited paper:
![image](https://user-images.githubusercontent.com/30303108/119017698-d94bf480-b9cd-11eb-9ce1-0b447a8f1f47.png)
The total throughput I get is 600 ops for Zipfian, 615 ops for 0%, 2%, and 333 ops for 100%, which is roughly consistent with what the paper claimed (650 ops for Zipfian, 0% and 2%, 230 ops for 100%).

The 99% latency I get is not all consistent with the results in the paper. The Zipfian workload latency is roughly the same. 2% and 100% latency is nearly the same as Zipfian latency, while 0% latency is about half of Zipfian latency at all datacenters (except JP).

### Experiment 2
The following shows the throughput vs. threads in each datacenter
![image](https://user-images.githubusercontent.com/30303108/119027979-85470d00-b9d9-11eb-8684-a7cfad6a5d5b.png)
The following shows the throughput vs. latency in each datacenter
**skew 0.9, 50% write:**
![image](https://user-images.githubusercontent.com/30303108/119021249-ca674100-b9d1-11eb-8dec-27915b831fb7.png)
**skew 0.6, 10% write:**
![image](https://user-images.githubusercontent.com/30303108/119028852-84fb4180-b9da-11eb-9477-df2564f0bc61.png)
For 0.9 skew, up to 900 threads, the throughput still increases linearly with the threads. And I didn't see latency increase significantly as the throughput increases. So I believe higher throughput is still achievable. The total throughput at 900 threads is about 30k ops. However, according to Fig. 12, the throughput of unmodified EPaxos at skew 0.9, 50% write is about 15k. I don't know how they got this number as they didn't mention how many clients are used. For 0.6 skew, there is a trend that throughput is out of linear growth with threads. The total throughput at 900 threads is about 37k ops, roughly consistent with the data point in Fig. 12 (40k).
![image](https://user-images.githubusercontent.com/30303108/119023348-52e6e100-b9d4-11eb-8ff6-236e7da4b2cd.png)

**Comment by shuaimu** [comment]
I wound't close this issue yet. I think there is something unsolved. I cannot recall exactly what but I remember I had a conversation with Xuhao about it.

**Comment by Stuart0l** [comment]
> I wound't close this issue yet. I think there is something unsolved. I cannot recall exactly what but I remember I had a conversation with Xuhao about it.

Yes. We talked about running the experiment in LAN to see if we can get different performance. I did that and updated the results in the most recent [comment](https://github.com/xlab-uiuc/slooo/issues/1#issuecomment-876573401) (I don't know if you have seen it). It's a bit different from the WAN performance but still looks not very good.

**Comment by tianyin** [comment]
I close this issue as nobody is working on it. So it is dead already.
