### ISSUE TITLE
Feature request: support Copilot

### ISSUE THREAD

**Issue by tianyin** [xlab-uiuc/slooo#13]
@varshith15 I wonder whether it's possible to support Copilot using Slooo,
https://github.com/princeton-sns/copilot/tree/main/src

It's a different protocol which is supposed to be resilient to single slow leader,
https://www.usenix.org/conference/osdi20/presentation/ngo

**Comment by varshith15** [comment]
I missed this issue completely, just saw this. Checking it.

Please post it on slack as well @tianyin. My github doesn't push notifications ;;(

**Comment by varshith15** [comment]
@tianyin I've had a glance at some of the code of copilot and it seems like it can be fit into slooo framework. I think we can port copilot to slooo.

**Comment by tianyin** [comment]
Awesome! Can you use Slooo to test it? 

Copilot has a fundamentally different architecture (no single leader), so I assume it needs a more generic designs -- or, putting in other words, if you can already support it well, you can prove Slooo more strongly.

**Comment by tianyin** [comment]
Let me close it for now. It will be needed for the paper.

**Comment by tianyin** [comment]
@Stuart0l actually did it, but not using `Slooo` and find very interesting behavior. We can later ask @Stuart0l for his scripts and rewrite in Slooo to reproduce the behavior and/or invite him as a coauthor.
