### ISSUE TITLE
A handheld tutorial on how to use Slooo

### ISSUE THREAD

**Issue by tianyin** [xlab-uiuc/slooo#16]
@varshith15 @Essoz 

Given that you will have 40 users, could you write a tutorial on how to use `Slooo` based on one system? 

Just pick one system (RethinkDB or MongoDB or whatever you like) and demonstrate each step and required code how to do the following:

* kill a node
* slow down CPU of a node
* slow down memory of a node

(you can choose a follower as the node)

The node can be either a leader or a follow, or both (e.g., in Copilot).

**Comment by varshith15** [comment]
I'll work on it, So just to be clear @tianyin
- Do you want a write-up on how to use Slooo on already ported systems like mongo?
or
- Do you want a write-up on how to port a new system to Slooo basically explaining the process and all the support fucntioons?

or both?

**Comment by Essoz** [comment]
I believe it is the second one. Illustrate step-by-step how we have ported systems like MongoDB to the tool and how to perform experiments.

**Comment by tianyin** [comment]
@varshith15 yes the 2nd one. 

I'm asking for a md file which explains step by step how to use Slooo to test a quorum system.

**Comment by tianyin** [comment]
btw, please prepare a local setup -- all the students will only do things on a local machine.
