### ISSUE TITLE
Could you move the sut code into ./SUT?

### ISSUE THREAD

**Issue by tianyin** [xlab-uiuc/slooo#18]
Please move 
* https://github.com/xlab-uiuc/slooo/tree/main/copilot
* https://github.com/xlab-uiuc/slooo/tree/main/mongo
* https://github.com/xlab-uiuc/slooo/tree/main/tidb
* https://github.com/xlab-uiuc/slooo/tree/main/rethink

into https://github.com/xlab-uiuc/slooo/tree/main/SUT

I dare not to move because I know the restructure could break your Python dependencies.

**Comment by varshith15** [comment]
done!
