### ISSUE TITLE
Please write this tutorial

### ISSUE THREAD

**Issue by tianyin** [xlab-uiuc/slooo#20]
@varshith15 @Essoz 

I posted #16 but didn't see any progress. I suspect you don't know how to write it. If that's the case, I prepare the writing as follows,
https://docs.google.com/document/d/1PNEr4W9QiRSeRIkXjEMApsrPZaqZAVhCZ3wEfN_fkA4/edit#

Could you please fill it ASAP?

I read through the codebase. The code is quite not clean :( 

There are dead code and redundant code (e.g., the temp.xsh and rethink.xsh under https://github.com/xlab-uiuc/slooo/tree/main/SUT/rethink). As a user, how can I figure out what is what?

Please put hard work as the code quality is really not on par to something for 40 users.

**Comment by varshith15** [comment]
Yes, the code is not very clean, ill do that.

**Comment by varshith15** [comment]
> I posted #16 but didn't see any progress. I suspect you don't know how to write it. 

I actually started writing it https://github.com/xlab-uiuc/slooo/blob/tutorial/tutorials/portinf.md

but yeah the one I'm writing is a bit more elaborate and explains all the methods in the classes.

ill fill this instead it seems simple https://docs.google.com/document/d/1PNEr4W9QiRSeRIkXjEMApsrPZaqZAVhCZ3wEfN_fkA4/edit#

**Comment by tianyin** [comment]
Thanks @varshith15 !

Writing the doc is also a good way to check the flow yourself and make sure things are working.

It's needed if you are working on a tool paper anyway.

**Comment by tianyin** [comment]
btw, please finish #32 before writing the tutorial. 

because #32 could change a number of things which need to be in the tutorial.

**Comment by tianyin** [comment]
replied to a thread:
> @Tianyin Xu I'll fill the tutorial doc you've shared by tomorrow morning (for you).

@varshith15 Sorry for the push. I want to have an estimation on when the tutorial will be ready. I need to roll it out to the students soon so I hope to have an estimation.
