### ISSUE TITLE
bad name

### ISSUE THREAD

**Issue by tianyin** [xlab-uiuc/slooo#22]
https://github.com/xlab-uiuc/slooo/blob/main/utils/general.xsh

`general` is a very bad name. It's hard for me to know what is `general` code.

It seems all the code there are related to VM ops? If that's the case, please rename it to `vm_utils`

**Comment by varshith15** [comment]
its basically the common code the one that is reused by all the databases.

**Comment by tianyin** [comment]
You can't simply remove it @varshith15 !!

See 
https://github.com/xlab-uiuc/slooo/blob/main/SUT/rethink/temp.xsh#L10

**Comment by varshith15** [comment]
smh. xonsh doesn't have a safe refactor option, hopefully, someone comes up with a xonsh ide extension soon.
updated it.
