### ISSUE TITLE
`faults`

### ISSUE THREAD

**Issue by tianyin** [xlab-uiuc/slooo#25]
It's good that you put fault implementations in `fault`.
https://github.com/xlab-uiuc/slooo/tree/main/faults

However, it is frustrating to read the code there.

Names like `1`, `2`, `3` are horrible names -- how can your users know what's going on by the names? Name them as the fault's name please (e.g., slow_cpu.sh).

Also, I don't find where `1.sh` is called. Are those deadcode?

Why they are not written in xonsh but in shell?

**Comment by varshith15** [comment]
Those shell scripts are old, please refer to faults_inject.xsh, ill clean up those shell scripts

**Comment by tianyin** [comment]
Please clean up.

Again, only you know what's old and new. Your users don't.
