### ISSUE TITLE
What are resources?

### ISSUE THREAD

**Issue by tianyin** [xlab-uiuc/slooo#26]
https://github.com/xlab-uiuc/slooo/tree/main/resources

Look like completely irrelevant stuff or dead code?

Can I remove them?

**Comment by varshith15** [comment]
workloads for ycsb and other resources which don't fit into slooo were supposed to go there

**Comment by tianyin** [comment]
Can you make things more clear? e.g., `vm_utils` or `workload_utils` rather than `general`?

**Comment by varshith15** [comment]
moved workloads to utils and reneamed general to common_utils
