### ISSUE TITLE
Need to add a reqs file

### ISSUE THREAD

**Issue by varshith15** [xlab-uiuc/slooo#29]
just a reminder to self.

**Comment by tianyin** [comment]
@Essoz Can you help with this?
https://github.com/xlab-uiuc/slooo/blob/main/requirments.txt

Can you write an MD file about how to install those packages?

**Comment by Essoz** [comment]
> @Essoz Can you help with this?
> https://github.com/xlab-uiuc/slooo/blob/main/requirments.txt
> 
> Can you write an MD file about how to install those packages?

I will do it. Just got vaccined. Sorry for not responding.

**Comment by tianyin** [comment]
I made it a md so please pull before write.

**Comment by tianyin** [comment]
thanks @Essoz
