### ISSUE TITLE
Clean `tests`

### ISSUE THREAD

**Issue by tianyin** [xlab-uiuc/slooo#32]
Please clean the tests you wrote in `/tests`

* rename the directory to `DBNAME` rather than some ambiguous name, i.e., rename `rethink` to `rethinkdb`.
* within each folder, name the main test case into `test_main.xsh` so people know what is the main file to look at (later, it is easy to script because one can just list all the `test_main` in the tests rather than needing to remember the name of the entry file.
* for `server_configs.json`, please either name it `server_config_local.json` or `server_config_azure.json`
* Please make sure that you refactor the code rather than introducing a lot of bugs such as in https://github.com/xlab-uiuc/slooo/issues/22#issuecomment-1019347068

**Comment by Essoz** [comment]
I am working on this.

**Comment by tianyin** [comment]
@Essoz please make sure your refactoring does not break things.

**Comment by tianyin** [comment]
Ooops, I see you already did it: https://github.com/xlab-uiuc/slooo/commit/bce16a7ae15f7c823aa8dfe785f2feab8e04ed2d

My question is how do you know you didn't break things...

Are you able to test out your changes?

**Comment by tianyin** [comment]
oh I see it's perhaps simple enough to validate.

**Comment by varshith15** [comment]
Actually there's an issue. We have a python package with the name rethinkdb as well so we can't name the directory name is rethinkdb

**Comment by tianyin** [comment]
That's exactly what I was worried about. Many fixes seem ad hoc and purely done at the text level. That's not a good way to fix stuff... We need some automated testing.

**Comment by tianyin** [comment]
> so we can't name the directory name is rethinkdb

feel free to name it back to `rethink`
