### ISSUE TITLE
We really have to run through the tests

### ISSUE THREAD

**Issue by tianyin** [xlab-uiuc/slooo#33]
just skimming through the code and bugs are so easy to be spotted
https://github.com/xlab-uiuc/slooo/blob/main/utils/quorum.xsh#L1

I'm not sure whether those bugs matter (it crashes or just ignore if it cannot find the package). 

We need to run through the RethinkDB or MongoDB to verify whether the code works.

**Comment by Essoz** [comment]
The paths and variables were renamed not all files have been updated correspondingly. I have fixed this obvious bug. Inspecting code for other possible bugs now.

**Comment by tianyin** [comment]
It's hard to rely on eyeballing to find all the bugs. We need a way to test the code.

Basically, we have to run the tests locally to make sure it works and works correctly.

**Comment by varshith15** [comment]
We plan to test the code once anyway so all these bugs will be resolved.

**Comment by tianyin** [comment]
wonderful!

Just a note that you only need to test the local mode.
