### ISSUE TITLE
Create a Docker image for the tutorial 

### ISSUE THREAD

**Issue by tianyin** [xlab-uiuc/slooo#35]
@varshith15 will write a dockerfile and test it.

**Comment by Essoz** [comment]
(An update from slack channel to keep things synchronized.)

Link to [docker image](https://hub.docker.com/r/eisvogle/slooo).
To store the image locally, use
```
docker pull eisvogle/slooo
docker save -o slooo_image.docker eisvogle/slooo 
```
The image has been uploaded to gdrive for your convenience.
https://drive.google.com/file/d/1DaJuOh2rXvvXfBAoPWzjTtMPbSgxaJ4Z/view?usp=sharing
