### ISSUE TITLE
We need a FAQ

### ISSUE THREAD

**Issue by tianyin** [xlab-uiuc/slooo#36]

**Comment by tianyin** [comment]
I don't think keeping pushing stuff into `req.md` is a good idea,
https://github.com/xlab-uiuc/slooo/commit/1f83a72262169ce5b72a6c76f510068ca82f5439

What we need is an FAQ and lists some stuff there.

**Comment by Essoz** [comment]
Hi prof! Should this FAQ be in the form of a markdown file?

**Comment by tianyin** [comment]
yes!

**Comment by tianyin** [comment]
and please call me @tianyin
