### ISSUE TITLE
Readings

### ISSUE THREAD

**Issue by tianyin** [xlab-uiuc/slooo#4]
Hi team, could you carefully read the Limpbench paper?
* https://ucare.cs.uchicago.edu/pdf/socc13-limplock.pdf

It's mostly closed related to our work and we need to position our work carefully.

We can pitch any or multiple of the following:
1. Slooo implements exactly what proposed in Limpbench, so we are a tool paper (hopefully that Limpbench is not released, is it?)
2. Slooo is much more extensible and can be used for many different types of systems.
3. Slooo is much more extensible and can be used to simulate more types of faults.
3. Slooo is not only more extensible but also more versatile (it can do X and Y and Z which is hard to be done by Limpbench)
4. Please let me know if there is anything you believe you can put on the table.

**Comment by varshith15** [comment]
Prof. @tianyin, I'm sorry, I completed missed this issue. My github update mails don't send a notification. I'll get right on it. 
Can you please post it on slack as well if and when you create a new issue.

**Comment by tianyin** [comment]
will do! @varshith15
