### ISSUE TITLE
"@Tianyin Xu can you confirm if anything else needs to be done?"

### ISSUE THREAD

**Issue by tianyin** [xlab-uiuc/slooo#41]
Sorry that I just had time to read over your answers again.

Yes, could you finish the following:
- [x]  For the faults onto leader, can you inject the faults during the workload, so that the results account for the leader re-election?
- [x] I can't access the figures in Q10 -- not sure why.
- [x] I still really understand the choice of using 50MB -- why not smaller?
- [x] In #37, you said "Not exactly sure what the reason might be. Have to investigate more." -- can you do this?

**Comment by varshith15** [comment]
>  For the faults onto leader, can you inject the faults during the workload, so that the results account for the leader re-election?

@tianyin This support has been implemented and I've run the experiment using it. The results are exactly the same. 15% of the requests fail due to the leader crash while there is leader re-election. But the rest of the throughput and latencies are almost similar to previously reported results.

**Comment by varshith15** [comment]
>  I can't access the figures in Q10 -- not sure why.

Updated the links, sorry.

**Comment by varshith15** [comment]
> In https://github.com/xlab-uiuc/slooo_internal/issues/37, you said "Not exactly sure what the reason might be. Have to investigate more." -- can you do this?

I think for this we needs deeper understanding of rethinks code, I'll try to look at the logs if I can find something.

**Comment by varshith15** [comment]
> I still really understand the choice of using 50MB -- why not smaller?

From my observation anything less than 50MB limit causes the leader to crash. The leader OOMs.
