### ISSUE TITLE
The new merged code broke the assignment

### ISSUE THREAD

**Issue by tianyin** [xlab-uiuc/slooo#46]
@plzdoo reported that the Assignment #2 is broken,
https://docs.google.com/document/d/1bVw1c9az67OvTKwVSBq41hWpOsuxLbrWNXcJxzkA9t8/edit

It is caused by the recent commit,
https://github.com/xlab-uiuc/slooo/commit/6bd8ff9e1978f7f7fa4c6a46b4f0f3de7719ecca

It seems we were not very careful in backward compatibility. @varshith15 

We will need to fix either the code or the doc. 

@plzdoo would you be willing to do it?

**Comment by varshith15** [comment]
@tianyin let me check the doc.

@plzdoo can you please explain the issue/bug?

**Comment by tianyin** [comment]
@varshith15 can you go through the doc and fix the bugs? 

I believe that you changed the code structure and many of the paths break.

**Comment by plzdoo** [comment]
> @tianyin let me check the doc.
> 
> @plzdoo can you please explain the issue/bug?

I first tried `xonsh run.xsh --system rethinkdb --workload ./YCSB/workloads/workloada --server-configs ./rethinkdb/server_configs_local.json --runtime 300 --exp-type follower --exps noslow,kill,1,5 --iters 5` but I got path for `server_configs_local.json` is not correct. 

Then I tried `xonsh run.xsh --system rethinkdb --workload ./YCSB/workloads/workloada --server-configs ./tests/rethink/server_configs_local.json --runtime 300 --exp-type follower --exps noslow,kill,1,5 --iters 5`

and these is what I got 
`umount: /dev/sdc: must be superuser to unmount.
cgdelete: cannot remove group 'db': No such file or directory
cgdelete: cannot remove group 'cpulow': No such file or directory
cgdelete: cannot remove group 'cpuhigh': No such file or directory
cgdelete: cannot remove group 'db': No such file or directory
sudo: /sbin/tc: command not found
umount: /dev/sdc: must be superuser to unmount.
cgdelete: cannot remove group 'db': No such file or directory
cgdelete: cannot remove group 'cpulow': No such file or directory
cgdelete: cannot remove group 'cpuhigh': No such file or directory
cgdelete: cannot remove group 'db': No such file or directory
sudo: /sbin/tc: command not found
umount: /dev/sdc: must be superuser to unmount.
cgdelete: cannot remove group 'db': No such file or directory
cgdelete: cannot remove group 'cpulow': No such file or directory
cgdelete: cannot remove group 'cpuhigh': No such file or directory
cgdelete: cannot remove group 'db': No such file or directory
sudo: /sbin/tc: command not found
umount: /dev/sdc: must be superuser to unmount.
Error accessing specified device /dev/sdc: No such file or directory
Usage: mkfs.xfs
/* blocksize */         [-b size=num]
/* metadata */          [-m crc=0|1,finobt=0|1,uuid=xxx,rmapbt=0|1,reflink=0|1]
/* data subvol */       [-d agcount=n,agsize=n,file,name=xxx,size=num,
                            (sunit=value,swidth=value|su=num,sw=num|noalign),
                            sectsize=num
/* force overwrite */   [-f]
/* inode size */        [-i perblock=n|size=num,maxpct=n,attr=0|1|2,
                            projid32bit=0|1,sparse=0|1]
/* no discard */        [-K]
/* log subvol */        [-l agnum=n,internal,size=num,logdev=xxx,version=n
                            sunit=value|su=num,sectsize=num,lazy-count=0|1]
/* label */             [-L label (maximum 12 characters)]
/* naming */            [-n size=num,version=2|ci,ftype=0|1]
/* no-op info only */   [-N]
/* prototype file */    [-p fname]
/* quiet */             [-q]
/* realtime subvol */   [-r extsize=num,size=num,rtdev=xxx]
/* sectorsize */        [-s size=num]
/* version */           [-V]
                        devicename
<devicename> is required unless -d name=xxx is given.
<num> is xxx (bytes), xxxs (sectors), xxxb (fs blocks), xxxk (xxx KiB),
      xxxm (xxx MiB), xxxg (xxx GiB), xxxt (xxx TiB) or xxxp (xxx PiB).
<value> is xxx (512 byte blocks).
mount: /data1: permission denied.
mount: /data1: permission denied.
umount: /dev/sdc: must be superuser to unmount.
Error accessing specified device /dev/sdc: No such file or directory
Usage: mkfs.xfs
/* blocksize */         [-b size=num]
/* metadata */          [-m crc=0|1,finobt=0|1,uuid=xxx,rmapbt=0|1,reflink=0|1]
/* data subvol */       [-d agcount=n,agsize=n,file,name=xxx,size=num,
                            (sunit=value,swidth=value|su=num,sw=num|noalign),
                            sectsize=num
/* force overwrite */   [-f]
/* inode size */        [-i perblock=n|size=num,maxpct=n,attr=0|1|2,
                            projid32bit=0|1,sparse=0|1]
/* no discard */        [-K]
/* log subvol */        [-l agnum=n,internal,size=num,logdev=xxx,version=n
                            sunit=value|su=num,sectsize=num,lazy-count=0|1]
/* label */             [-L label (maximum 12 characters)]
/* naming */            [-n size=num,version=2|ci,ftype=0|1]
/* no-op info only */   [-N]
/* prototype file */    [-p fname]
/* quiet */             [-q]
/* realtime subvol */   [-r extsize=num,size=num,rtdev=xxx]
/* sectorsize */        [-s size=num]
/* version */           [-V]
                        devicename
<devicename> is required unless -d name=xxx is given.
<num> is xxx (bytes), xxxs (sectors), xxxb (fs blocks), xxxk (xxx KiB),
      xxxm (xxx MiB), xxxg (xxx GiB), xxxt (xxx TiB) or xxxp (xxx PiB).
<value> is xxx (512 byte blocks).
mount: /data2: permission denied.
mount: /data2: permission denied.
umount: /dev/sdc: must be superuser to unmount.
Error accessing specified device /dev/sdc: No such file or directory
Usage: mkfs.xfs
/* blocksize */         [-b size=num]
/* metadata */          [-m crc=0|1,finobt=0|1,uuid=xxx,rmapbt=0|1,reflink=0|1]
/* data subvol */       [-d agcount=n,agsize=n,file,name=xxx,size=num,
                            (sunit=value,swidth=value|su=num,sw=num|noalign),
                            sectsize=num
/* force overwrite */   [-f]
/* inode size */        [-i perblock=n|size=num,maxpct=n,attr=0|1|2,
                            projid32bit=0|1,sparse=0|1]
/* no discard */        [-K]
/* log subvol */        [-l agnum=n,internal,size=num,logdev=xxx,version=n
                            sunit=value|su=num,sectsize=num,lazy-count=0|1]
/* label */             [-L label (maximum 12 characters)]
/* naming */            [-n size=num,version=2|ci,ftype=0|1]
/* no-op info only */   [-N]
/* prototype file */    [-p fname]
/* quiet */             [-q]
/* realtime subvol */   [-r extsize=num,size=num,rtdev=xxx]
/* sectorsize */        [-s size=num]
/* version */           [-V]
                        devicename
<devicename> is required unless -d name=xxx is given.
<num> is xxx (bytes), xxxs (sectors), xxxb (fs blocks), xxxk (xxx KiB),
      xxxm (xxx MiB), xxxg (xxx GiB), xxxt (xxx TiB) or xxxp (xxx PiB).
<value> is xxx (512 byte blocks).
mount: /data3: permission denied.
mount: /data3: permission denied.
sysctl: setting key "vm.swappiness", ignoring: Read-only file system
sysctl: setting key "vm.swappiness", ignoring: Read-only file system
sysctl: setting key "vm.swappiness", ignoring: Read-only file system
Recursively removing directory /data1/rethinkdb_data1/tmp
Recursively removing directory /data1/rethinkdb_data1/tmp
taskset: failed to set pid 419's affinity: Invalid argument
taskset: failed to set pid 434's affinity: Invalid argument`


Then I tried with sudo and I got `ModuleNotFoundError: No module named 'tests'`.

**Comment by tianyin** [comment]
there is no `tests` directory as before (I believe @varshith15 changed `tests` into `quorums`). 

I think the original codetree is broken and needs to be fixed.

**Comment by varshith15** [comment]
I am updating the tutorial doc

**Comment by varshith15** [comment]
@plzdoo I've updated the tutorial. The CLI options have now been moved to [run.yaml](https://github.com/xlab-uiuc/slooo/blob/main/utils/run.yaml) which you'll now have to provide while running the command.

**Comment by plzdoo** [comment]
> @plzdoo I've updated the tutorial. The CLI options have now been moved to [run.yaml](https://github.com/xlab-uiuc/slooo/blob/main/utils/run.yaml) which you'll now have to provide while running the command.

Got it!. I think the version of docker image is a little fall behind rn.

**Comment by varshith15** [comment]
> Got it!. I think the version of docker image is a little fall behind rn.

The docker environment is the same, just update the Slooo repo in the docker before you run tests
