### ISSUE TITLE
Paper wrtting

### ISSUE THREAD

**Issue by varshith15** [xlab-uiuc/slooo#6]
Prof. @tianyin, I think we are almost done with  porting the code (MongoDB, RethinkDB, TiDB, Redis, PolarDB)
(Hopefully we will have a working version ( version 1 ) of the framework by the end of the week). 

We want to start think about the paper now. And I am not exactly sure as to where to start. 
Could you please give some pointers on this? As to where to start and what to do.

**Comment by tianyin** [comment]
@varshith15 @Essoz @TheEnthralled 

I created the paper repo,
https://github.com/xlab-uiuc-prep/slooo_tool_prep
and have added you there.  Let me know if you can't access.

I wrote the basic paper structures.

You need to install LaTeX first to be able to compile the PDF. If you have LaTeX, just type `make` (there is a Makefile in the repo).

My advice is to write the following sections *in order*:
* Section 2 Interface
* Section 3 Design and Implementation
* Section 4 Evaluation

I can help write the other sections, namely Intro, Abstract, and Conclusion (so don't worry about those).

You should use the paper to calibrate the technical work.
