### ISSUE TITLE
 Action plan #2 (Deadline Oct 8, Tool should be ready by then) #3 

### ISSUE THREAD

**Issue by TheEnthralled** [xlab-uiuc/slooo#7]
Here's the new action plan for this week. Feel free to add to it or clarify things.

Andrei:
- [ ] Test Redis slooo code

Varshith:
- [ ] Test TiDB code

Yuxuan:
- [x] Make more config-friendly interface for injecting/specifying fail-slow faults; "For example, a user can feed path to a specific slowness-config file when running run.xsh and then slow.xsh will read from that file when injecting slowness."
- [x] Modify PolarDB code (use init_disk instead)

Future goals:

- Users should write functions to format the benchmark results into a unified format required by the framework.
- Porting/implementing other databases (which ones in particular TBD).
- Making the framework even more generalizable.

**Comment by varshith15** [comment]
9/22/2021: Sync-up
Summary:

- Me and @TheEnthralled  were busy the past week so there wasn't much progress made from our side.
- @Essoz has ported and tested the polarDB and will now try to look for improvements in the framework.
- TiDB doesn't seem to be straight forward like rethink and mongo were so I just need a little bit more time to test it.
- @TheEnthralled has come up with a great suggestion to use a super class for all DBs to inherit from like [this](https://github.com/xlab-uiuc/slooo/blob/main/scripts/utils/exp.xsh), so the code needs to be updated accordingly. 

Prof. @tianyin We were hoping if you could have a glance at the code and provide some suggestions / improvements please(There's a lot of code cleanup that needs to be done btw).
And also are we going to present results for the experiments in our tool paper? like in depfast ? If so are we going to use the old figures or run everything again?

**Comment by tianyin** [comment]
> We were hoping if you could have a glance at the code and provide some suggestions / improvements

I can do that. But, before that, I would suggest you to write the middle section of the tool paper, so I can read from a reviewer's perspective,
https://github.com/xlab-uiuc-prep/slooo_tool_prep/blob/main/interface.tex
https://github.com/xlab-uiuc-prep/slooo_tool_prep/blob/main/design.tex

> @TheEnthralled has come up with a great suggestion to use a super class for all DBs to inherit from like this

This is a great suggestion. If you read the paper template, the success of the work heavily depends on how usable the framework is. So, you do need to provide good abstractions and interfaces to help your users write tests easily. If they are required to write all the shell scripts, it's hard to justify why your work is useful.

> are we going to present results for the experiments in our tool paper? like in depfast ? If so are we going to use the old figures or run everything again?

I believe you guys already have some results in the old posts @varshith15 @TheEnthralled and @Essoz posted here and there. We can reuse the results. If there are more needed, we can run some new experiments.

I don't have a clear picture about what has been done and what still needs to be done. I hope to read a draft 
https://github.com/xlab-uiuc-prep/slooo_tool_prep
so I can have a clear idea.

**Comment by tianyin** [comment]
> TiDB doesn't seem to be straight forward like rethink and mongo were so I just need a little bit more time to test it.

This is great! 

Note that when I say "great", I do not mean it's great because you have more work to do :) 

It is great because if you find it hard to write tests for TiDB, it means your framework needs to be extended. It is a great case study in your paper and make your paper more interesting.
